language: java
before_install:
  - sudo apt-get -y install jq
  - java -Xmx32m -version
before_script:
  - ls -lah
  - google-chrome-stable --version
addons:
  chrome: stable
  apt:
    packages:
      - openjdk-8-jdk
env:
  global:
    - CHROME_PROPERTIES="chrome.properties"
    - WITH_PARAMS="-Ddriver=chrome -Dchrome.capabilities.path=$CHROME_PROPERTIES" #add -ntp when maven will be >=3.6.1 on travis
    - GROUP_ID="com.epam.jdi"
    - NOPO_TESTS="jdi-bdd-no-po-tests"
    - NOPO_TESTS_PROPERTY="test-examples/jdi-bdd-no-po-tests"
    - BDD_TESTS="jdi-bdd-tests"
    - BOOTSTRAP_TESTS="jdi-light-bootstrap-tests"
    - HTML_TESTS="jdi-light-html-tests"
    - ANGULAR_TESTS="jdi-light-angular-tests"
    - EXAMPLES="jdi-light-examples"
    - EXAMPLES_PROPERTY="test-examples/jdi-light-examples"
    - PERFORMANCE="jdi-performance"
    - PERFORMANCE_PROPERTY="test-examples/jdi-performance"
    - JDI_LIGHT_UNIT_TESTS="jdi-light"
    - CHROME_ARGS="--headless"
    - PATH="$JAVA_HOME/bin:$PATH"
stages:
  - prepare
  - compile
  - test
  - reports
testsbdd: &testsbdd
  stage: test
  name: "Run tests - bdd"
  script:
    - mvn -ntp install -DskipTests
    - echo arguments=$CHROME_ARGS > "./$BDD_TESTS/src/test/resources/$CHROME_PROPERTIES"
    - mvn verify $WITH_PARAMS -pl $GROUP_ID:$BDD_TESTS
testsbootstrap: &testsbootstrap
  stage: test
  name: Run tests - bootstrap
  script:
    - mvn -ntp install -DskipTests
    - echo arguments=$CHROME_ARGS > "./$BOOTSTRAP_TESTS/src/test/resources/$CHROME_PROPERTIES"
    - mvn verify $WITH_PARAMS -pl $GROUP_ID:$BOOTSTRAP_TESTS
testsexamples: &testsexamples
  stage: test
  name: Run tests - examples
  script:
    - mvn -ntp install -DskipTests
    - echo arguments=$CHROME_ARGS > "./$EXAMPLES_PROPERTY/src/test/resources/$CHROME_PROPERTIES"
    - mvn verify $WITH_PARAMS -pl $GROUP_ID:$EXAMPLES
testsperformance: &testsperformance
  stage: test
  name: Run tests - performance
  script:
    - mvn -ntp install -DskipTests
    - echo arguments=$CHROME_ARGS > "./$PERFORMANCE_PROPERTY/src/test/resources/$CHROME_PROPERTIES"
    - mvn verify $WITH_PARAMS -pl $GROUP_ID:$PERFORMANCE
testsunit: &testsunit
  stage: test
  name: Run tests - jdi-light-unit-tests
  script:
    - mvn -ntp install -DskipTests
    - mvn verify -pl $GROUP_ID:$JDI_LIGHT_UNIT_TESTS
testsangular: &testsangular # alias-anchor approach does not work with angular
  stage: test
  name: Run tests - angular
  script:
    - mvn -ntp install -DskipTests
    - echo arguments=$CHROME_ARGS > "./$ANGULAR_TESTS/src/test/resources/$CHROME_PROPERTIES"
    - mvn verify $WITH_PARAMS -pl $GROUP_ID:$ANGULAR_TESTS
testshtml: &testshtml
  stage: test
  name: Run tests - html
  script:
    - mvn -ntp install -DskipTests
    - echo arguments=$CHROME_ARGS > "./$HTML_TESTS/src/test/resources/$CHROME_PROPERTIES"
    - mvn verify $WITH_PARAMS -pl $GROUP_ID:$HTML_TESTS
jobs:
  include:
    - stage: prepare
      name: Welcome to jdi
      script:
        - echo ------------------- WELCOME TO JDI ----------------------
        - mvn --version #it is helpful
    - stage: compile
      name: Compile jdi code
      script:
        - mvn install -DskipTests
# TODO: Lines below were commented to reduce build time and fine-tune the reporting process
#        - mvn verify $WITH_PARAMS -pl $GROUP_ID:$ANGULAR_TESTS
#    - <<: *testsbdd
#      name: "Run tests - bdd JDK8"
#      jdk: openjdk8
#    - <<: *testsbdd
#      name: "Run tests - bdd JDK10"
#      jdk: openjdk10
#    - <<: *testsbdd
#      name: "Run tests - bdd JDK11"
#      jdk: openjdk11
#    - <<: *testsbootstrap
#      name: "Run tests - bootstrap JDK8"
#      jdk: openjdk8
#    - <<: *testsbootstrap
#      name: "Run tests - bootstrap JDK10"
#      jdk: openjdk10
#    - <<: *testsbootstrap
#      name: "Run tests - bootstrap JDK11"
#      jdk: openjdk11
    - stage: test
      name: Run tests - angular
      jdk: openjdk8
      script:
        - mvn -ntp install -DskipTests
        - echo arguments=$CHROME_ARGS > "./$ANGULAR_TESTS/src/test/resources/$CHROME_PROPERTIES"
#    - <<: *testshtml
#      name: "Run tests - html JDK8"
#      jdk: openjdk8
#    - <<: *testshtml
#      name: "Run tests - html JDK10"
#      jdk: openjdk10
#    - <<: *testshtml
#      name: "Run tests - html JDK11"
#      jdk: openjdk11
    - <<: *testsexamples
      name: "Run tests - examples JDK8"
      jdk: openjdk8
    - <<: *testsexamples
      name: "Run tests - examples JDK10"
      jdk: openjdk10
    - <<: *testsexamples
      name: "Run tests - examples JDK11"
      jdk: openjdk11
    - <<: *testsperformance
      name: "Run tests - performance JDK8"
      jdk: openjdk8
    - <<: *testsperformance
      name: "Run tests - performance JDK10"
      jdk: openjdk10
    - <<: *testsperformance
      name: "Run tests - performance JDK11"
      jdk: openjdk11
#    - <<: *testsunit
#      name: "Run tests - jdi-light-unit-tests JDK8"
#      jdk: openjdk8
#    - <<: *testsunit
#      name: "Run tests - jdi-light-unit-tests JDK10"
#      jdk: openjdk10
#    - <<: *testsunit
#      name: "Run tests - jdi-light-unit-tests JDK11"
#      jdk: openjdk11
    - stage: reports
      name: Deploy allure reports to netlify
      script:
        - npm install -g allure-commandline
        - npm install -g netlify-cli
        - allure --version
        - source reports.sh
        - deployAllureResults
after_failure:
  - echo "Build was failed"
after_success:
  - echo "Build was successful"
after_script:
  # following 4 lines are to rename allure-results dir to allure-results-<JDK VERSION>
  - find -type d -regex ".*/jdi.*/target/allure-results"
  - ALLURE_RESULTS=$(find jdi-*/target/ -type d -name "allure-results")
  - ALLURE_RESULTS_JDK=$ALLURE_RESULTS-$TRAVIS_JDK_VERSION
  - mv $ALLURE_RESULTS $ALLURE_RESULTS_JDK
  - echo "$ALLURE_RESULTS dir has been renamed to $ALLURE_RESULTS_JDK"
  # further actions
  - source reports.sh
  - grubAllureResults
  - du -d 1 -h ./
  - ls -la
# extra time during long builds
install:
  - travis_wait
